# Site settings
title: BaoshengYu's Blog.
email: yubaosheng1011@gmail.com
author: BaoshengYu
description: "This is BaoshengYu's Blog.Welcome to my blog."
baseurl: /blog
url: "http://codeybs.github.io/blog"

# Build settings
markdown: kramdown
permalink: pretty
